// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz4TpkP2_eVeHANjrX2wjzHq96Jaj4DrA',
    appId: '1:639289966553:web:e473f448115e6ac2dc23c8',
    messagingSenderId: '639289966553',
    projectId: 'backend-9c1e1',
    authDomain: 'backend-9c1e1.firebaseapp.com',
    databaseURL: 'https://backend-9c1e1-default-rtdb.firebaseio.com/',
    storageBucket: 'backend-9c1e1.appspot.com',
    measurementId: 'G-R5NE5B9HJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2cAmPIQdt62Z8kY7Z2ze4UbX0oRFtW5c',
    appId: '1:639289966553:android:f8e6a51c64853ceedc23c8',
    messagingSenderId: '639289966553',
    projectId: 'backend-9c1e1',
    storageBucket: 'backend-9c1e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXLAGvvEJoA6rnycSC_PytYhVeFC1eAdg',
    appId: '1:639289966553:ios:c6b26ab5bf34377edc23c8',
    messagingSenderId: '639289966553',
    projectId: 'backend-9c1e1',
    storageBucket: 'backend-9c1e1.appspot.com',
    iosBundleId: 'com.example.backend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXLAGvvEJoA6rnycSC_PytYhVeFC1eAdg',
    appId: '1:639289966553:ios:64a4aa3c641900a3dc23c8',
    messagingSenderId: '639289966553',
    projectId: 'backend-9c1e1',
    storageBucket: 'backend-9c1e1.appspot.com',
    iosBundleId: 'com.example.backend.RunnerTests',
  );
}
